### ISSUE TITLE
Dropped pins in case of enable/disable error

### ISSUE THREAD

**Issue by marius-meissner** [barafael/cd74hc4067#1]
Thank you for this neat crate, especially with the good test coverage and the typestate implementation.

As the enable/disable functions are consuming, the struct including the pins is dropped:
https://github.com/barafael/cd74hc4067-rs/blob/37608f73805e2d82c7f9b21f4460dd55dbff622a/cd74hc4067/src/lib.rs#L93

However, this can be a problem for some systems that operate a singleton principle for GPIO pins. On such systems, it is only possible to obtain a pin instance once. An example of this is the [RP2040 HAL](https://docs.rs/rp2040-hal/latest/rp2040_hal/gpio/pin/index.html):
> It is not possible for users to create new instances of a [Pin](https://docs.rs/rp2040-hal/latest/rp2040_hal/gpio/pin/struct.Pin.html). Singleton instances of each pin are made available to users through the [Pins](https://docs.rs/rp2040-hal/latest/rp2040_hal/gpio/pin/bank0/struct.Pins.html) struct.

Of course, there are workaround (e.g. wrapped pins with internal reference), but that would be very inconvenient and not elegant.

I see two possible solutions in case of an error:
1) Releasing the internal pins as part of the Error enum
2) Return a tuple containing the error + struct with the old state

Personally, I tend towards the second solution
What do you think?

Looking forward to your feedback. 

PS: If desired, I can also support with an appropriate PR.

**Comment by barafael** [comment]
For sure, thank you for reporting the problem! The joys of move semantics :) the fix is straightforward, I also think solution 2 is preferable. I'll update on Monday, unless you get to it first :)

**Comment by marius-meissner** [comment]
Thank you for the fast answer. I quickly implemented the changes so that I can use them in another project.
Anyway no hurry :)

**Comment by barafael** [comment]
Fixed in #2
